[project]
name = "instagram-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mqsanatgar", email = "masoud.sanatgar.quchani@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-debug-toolbar>=8.0.0",
    "djangorestframework>=3.18.1",
    "pillow>=12.3.0",
    "psycopg>=3.3.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
instagram-project = "instagram_project:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
