# Generated by Django 6.1.1 on 2026-09-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="instagram.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
