# Generated by Django 6.1.1 on 2026-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_alter_comment_post_alter_post_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.TextField(default="Hello", max_length=1000),
        ),
    ]
